name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev    
    - uses: actions/checkout@v4
    - name: run programs
      working-directory: programs
      run: make all
